basePath: /
definitions:
  dto.CommentRequestBody:
    properties:
      message:
        type: string
      photo_id:
        type: integer
      user_id:
        type: integer
    type: object
  entities.Comment:
    properties:
      created_at:
        type: string
      id:
        type: integer
      message:
        type: string
      photoID:
        type: integer
      updated_at:
        type: string
      userID:
        type: integer
    type: object
  entities.Photo:
    properties:
      caption:
        type: string
      comments:
        items:
          $ref: '#/definitions/entities.Comment'
        type: array
      created_at:
        type: string
      id:
        type: integer
      imageID:
        type: integer
      photo_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
      userID:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: devyad@gmail.com
    name: API Support
  description: This is a simple services for managing cars
  license:
    name: Apace 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Insta Clone Api
  version: "1.0"
paths:
  /comment:
    get:
      consumes:
      - application/json
      description: Get details of all comment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Comment'
      security:
      - Bearer: []
      summary: Get details
      tags:
      - Comment
    post:
      consumes:
      - application/json
      description: Create Comment corresponding to the photo id in param
      parameters:
      - description: create comment
        in: body
        name: dto.CommentRequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.CommentRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Comment'
      security:
      - Bearer: []
      summary: Post comment for a given id
      tags:
      - Comment
  /comment/{Id}:
    delete:
      consumes:
      - application/json
      description: Delete the comment corresponding to the input id
      parameters:
      - description: ID of the comment to be deleted
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No content
      security:
      - Bearer: []
      summary: Delete comment identified by given id
      tags:
      - Comment
    get:
      consumes:
      - application/json
      description: Get details of comment corresponding to the input id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Comment'
      security:
      - Bearer: []
      summary: Get details for a given id
      tags:
      - Comment
    patch:
      consumes:
      - application/json
      description: Update details of Comment corresponding to the input id
      parameters:
      - description: ID of the comment to be updated
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Comment'
      security:
      - Bearer: []
      summary: Update comment identified by given id
      tags:
      - Comment
  /photo:
    get:
      consumes:
      - application/json
      description: Get details of all photo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Photo'
      security:
      - Bearer: []
      summary: Get details
      tags:
      - Photo
    post:
      consumes:
      - application/json
      description: Create Photo corresponding to the photo id in param
      parameters:
      - description: create photo
        in: body
        name: entities.Photo
        required: true
        schema:
          $ref: '#/definitions/entities.Photo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Photo'
      security:
      - Bearer: []
      summary: Post Photo for a given id
      tags:
      - Photo
  /photo/{Id}:
    delete:
      consumes:
      - application/json
      description: Delete the photo corresponding to the input id
      parameters:
      - description: ID of the photo to be deleted
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No photo
      security:
      - Bearer: []
      summary: Delete photo identified by given id
      tags:
      - Photo
    get:
      consumes:
      - application/json
      description: Get details of photo corresponding to the input id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Photo'
      security:
      - Bearer: []
      summary: Get details for a given id
      tags:
      - Photo
    patch:
      consumes:
      - application/json
      description: Update details of Photo corresponding to the input id
      parameters:
      - description: ID of the photo to be updated
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Photo'
      security:
      - Bearer: []
      summary: Update photo identified by given id
      tags:
      - Photo
  /social-media/{Id}:
    delete:
      consumes:
      - application/json
      description: Delete the social media corresponding to the input id
      parameters:
      - description: ID of the social media to be deleted
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No content
      security:
      - Bearer: []
      summary: Delete social media identified by given id
      tags:
      - Social Media
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
